spring.application.name=task-management-app
spring.datasource.url=${SPRING_DATASOURCE_URL:\
jdbc:mysql://localhost:3306/task_management_db?\
serverTimezone=UTC}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:password}

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=validate

spring.jpa.show-sql=true

spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml

app.admin.username=${ADMIN_USERNAME:admin}
app.admin.email=${ADMIN_EMAIL:admin@gmail}
app.admin.password=${ADMIN_PASSWORD}
app.admin.first-name=${ADMIN_FIRST_NAME:Admin}
app.admin.last-name=${ADMIN_LAST_NAME:User}

jwt.expiration=${JWT_EXPIRATION:3000000}
jwt.secret=${JWT_SECRET}
